### PR TITLE
Feat/Create Basic Pong RL Agent

### PR DESCRIPTION
**Pull request by kiritowu**
Completed basic RL Agent with pretrained weights on Dueling DQN trained on OpenAI Gym environment. This paved the path for exposing AI agents to the final Human vs AI match-off game engine.

### CODE REVIEW

**Comment by Tien-Cheng** [comment]
You gonna merge it? Lgtm

**Comment by Tien-Cheng** [comment]
Just to check, looking at the pre-processing code, does my game score need to be 20 px tall?

**Comment by Tien-Cheng** [comment]
@kiritowu

**Comment by kiritowu** [comment]
> Just to check, looking at the pre-processing code, does my game score need to be 20 px tall?

Doesn't need to be, I can create another method to preprocess the image before parsing to the NN

**Comment by kiritowu** [comment]
> You gonna merge it? Lgtm

Ok merge now. Thanks

**Pull request merged**
